### PR TITLE
Discontiuous plotting

### LINKED ISSUE #8: Cell data & higher order plotting
- [x] How do we plot stuff for cell dependent data instead of nodal data? Is it possible with Makie?
- [x] How to plot higher order stuff, possible in Makie?

### LINKED ISSUE #10: Visualization on quads underresolved
Splitting quads into two triangles underresolves the solution, because we loose one of the diagonal modes. This can be fixed by splitting quads into four triangles instead. The same problem occurs in 3D.

### PR DESCRIPTION
**Pull request by termi-official**
This PR generalizes plotting and can be the foundation for high order plotting. Also it resolves #10 and at least partially resolves #8 .

Tested against https://github.com/Ferrite-FEM/Ferrite.jl/pull/392 with the reported benchmark. 

Crouzeix-Raviart example:
heat-crouzeix-raviart

# TODOs
* [x] Visualizing discontinuous data
* [x] Make vectorial and multi-field problems work again
* [ ] Adaptive triangle data structure with iterator (check against possible implementation through tess shaders)

### CODE REVIEW

**Comment by termi-official** [comment]
ping @koehlerson How should we handle this? We can either merge this into the master or we can merge the master back into this branch for now and leave it open. Would like to not touch the tessellation for now, because this could turn into a waste of time. Not super urgent because the L2 functions are not merged into Ferrite yet.

**Comment by koehlerson** [comment]
I'd say that we resolve the conflicts and merge it into master, it's not like that we loose anything by merging it, lots of master stuff needs to be rewritten anyway at some point. I can take care of resolving conflicts if you don't have time for it

**Comment by termi-official** [comment]
If the time invest is not too high for you, then give it a try by merging the master into this first. Testing this should be rather easy. You can take the convergence study in Ferrite PR 392 and just swap the interpolation. Last time I tested against every element in the PR (can also provide an example for L2P0). 

However if this means too much time invest then I can merge this within the next weeks.

**Comment by koehlerson** [comment]
open issues after merging master 

- [ ] drawing faces/edges ( in 2 and 3D, respectively)
- [ ] cell label positioning 
- [ ] update of `u` for quasi-static or time dependent stuff doesn't propagate through the plot

**Comment by termi-official** [comment]
2D tested with the following script against Ferrite 0.3.3

```julia
using Ferrite, SparseArrays

# Manufactured Solution 
function u_anal(x) 
    val = 1.0
    for x_i in x
        val *= sin(x_i)
    end
    val
end

dim = 2
grid = generate_grid(Triangle, (2, 2), Vec(0.0,0.0), Vec(float(π), float(π)));
∂Ω = union(getfaceset.((grid, ), ["left", "right", "top", "bottom"])...);

ip = Ferrite.CrouzeixRaviart{dim, 1}()
ip_geo = Lagrange{dim, RefTetrahedron, 1}()
qr = QuadratureRule{dim, RefTetrahedron}(4)
cellvalues = CellScalarValues(qr, ip, ip_geo);
# for all the elements.
dh = DofHandler(grid)
push!(dh, :u, 1, ip)
close!(dh);

K = create_sparsity_pattern(dh);

ch = ConstraintHandler(dh);
dbc = Dirichlet(:u, ∂Ω, (x, t) -> 0)
add!(ch, dbc);
close!(ch)
update!(ch, 0.0);

function doassemble(cellvalues::CellScalarValues{dim}, K::SparseMatrixCSC, dh::DofHandler, u_anal) where {dim}
    n_basefuncs = getnbasefunctions(cellvalues)
    Ke = zeros(n_basefuncs, n_basefuncs)
    fe = zeros(n_basefuncs)

    f = zeros(ndofs(dh))
    assembler = start_assemble(K, f)

    @inbounds for cell in CellIterator(dh)
        fill!(Ke, 0)
        fill!(fe, 0)

        reinit!(cellvalues, cell)
        coords = getcoordinates(cell)

        for q_point in 1:getnquadpoints(cellvalues)
            dΩ = getdetJdV(cellvalues, q_point)
            coords_qp = spatial_coordinate(cellvalues, q_point, coords)
            for i in 1:n_basefuncs
                v  = shape_value(cellvalues, q_point, i)
                ∇v = shape_gradient(cellvalues, q_point, i)

                fe[i] += u_anal(coords_qp) * v * dΩ

                for j in 1:n_basefuncs
                    ∇u = shape_gradient(cellvalues, q_point, j)
                    Ke[i, j] += (∇v ⋅ ∇u) * dΩ
                end
            end
        end

        assemble!(assembler, celldofs(cell), fe, Ke)
    end
    return K, f
end
K, f = doassemble(cellvalues, K, dh, u_anal);

apply!(K, f, ch)
u = K \ f;


using FerriteVis, WGLMakie

plotter = MakiePlotter(dh,u);
FerriteVis.surface(plotter)
```

**Pull request merged**
